### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by twoyoungtwosimple** [masweetman/issue_charts#37]
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

**Comment by rogerpfaff** [comment]
Can you provide the log output as described in the error message? You can find it under <redmine_root>/logs/

**Comment by twoyoungtwosimple** [comment]
> Can you provide the log output as described in the error message? You can find it under <redmine_root>/logs/
Hi，Thank you !   


Started GET "/redmine/projects/quality_project/charts" for 127.0.0.1 at 2019-04-25 15:21:25 +0800
Processing by ChartsController#index as HTML
  Parameters: {"project_id"=>"quality_project"}
  Current user: root (id=1)
  Rendered plugins/issue_charts/app/views/charts/index.html.erb within layouts/base (438.3ms)
Completed 500 Internal Server Error in 493ms (ActiveRecord: 24.4ms)

LoadError (cannot load such file -- sass):
  config/initializers/10-patches.rb:221:in `rails_asset_id'
  config/initializers/10-patches.rb:200:in `asset_path_with_asset_id'
  app/helpers/application_helper.rb:1398:in `javascript_include_tag'
  plugins/issue_charts/app/views/charts/index.html.erb:1:in `_d9d793966cd833fb23829bc071d41676'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by twoyoungtwosimple** [comment]
> Can you provide the log output as described in the error message? You can find it under <redmine_root>/logs/

My server is in China, I can't access <%= javascript_include_tag 'https://www.google.com/jsapi', 'chartkick' %>, how should I replace it?
